'use client';
import { useState } from 'react';
import { Check, CloudDownload, Database, RefreshCw } from 'lucide-react';
import { api, date, number, type BaseInfo, type Job } from '@/lib/api';

export default function Base({ base, job, setJob }: { base: BaseInfo; job: Job; setJob: (value: Job) => void }) {
  const [download, setDownload] = useState(!base.disponivel);
  const [error, setError] = useState('');
  const [starting, setStarting] = useState(false);
  const running = job.status === 'rodando';
  async function start() { setStarting(true); setError(''); try { setJob(await api<Job>('tarefas', { baixar_cadastro: download })); } catch (e) { setError((e as Error).message); } finally { setStarting(false); } }
  return <section className="base-layout">
    <div className="base-info"><div className="base-title"><Database size={24} /><div><span className="eyebrow">Seu acervo local</span><h2>Base do Ceará</h2></div><span className="tag">{base.disponivel ? 'Disponível' : 'A preparar'}</span></div><dl className="base-facts"><div><dt>Empresas com contato</dt><dd>{number(base.contatos)}</dd></div><div><dt>Municípios</dt><dd>{number(base.municipios)}</dd></div><div><dt>Ramos de atividade</dt><dd>{number(base.ramos)}</dd></div><div><dt>Versão do cadastro</dt><dd>{date(base.versao_receita)}</dd></div><div><dt>Base gerada em</dt><dd>{date(base.gerado_em)}</dd></div><div><dt>Armazenamento do banco</dt><dd>{base.tamanho_mb ?? 0} MB</dd></div></dl><p className="help-text">Os dados estão no diretório <code>data/</code> deste projeto ou no caminho definido em <code>CEARA_DATA_DIR</code>.</p>
      <div className="base-provenance"><h3>Como ler estes dados</h3><p>Dados Abertos CNPJ da Receita Federal, processados para o Ceará. A base reúne estabelecimentos ativos na data do cadastro com e-mail ou celular aproveitável.</p><p>O score é uma priorização para serviços digitais. “Sem domínio próprio” deriva do e-mail. O ano de abertura não contém mês ou dia.</p><p>Malhas e códigos de municípios: IBGE.</p></div>
    </div>
    <div className="base-operations"><div className="update-section"><span className="eyebrow">Manutenção</span><h2>Atualizar com tranquilidade</h2><p>A nova base é gerada em uma pasta temporária e validada antes de entrar em uso. Enquanto isso, a versão atual continua disponível.</p><label className="download-choice"><input type="checkbox" checked={download} onChange={e => setDownload(e.target.checked)} disabled={running} /><span><strong>Baixar novo cadastro</strong><small>Os arquivos de origem são nacionais: o download pode consumir vários GB e demorar. Apenas dados do Ceará são preservados.</small></span></label><button className="button primary" disabled={running || starting} onClick={() => void start()}>{download ? <CloudDownload size={17} /> : <RefreshCw size={17} />}{running ? 'Atualização em andamento' : starting ? 'Iniciando…' : download ? 'Baixar e atualizar Ceará' : 'Regenerar com dados locais'}</button>{error && <p className="inline-error" role="alert">{error}</p>}{job.status === 'concluido' && <p className="success-message"><Check size={16} /> Nova base disponível.</p>}{job.status === 'erro' && <p className="inline-error">A atualização falhou. A base anterior foi preservada.</p>}</div>
      {job.linhas.length > 0 && <div className="job-log"><header><strong>Acompanhamento</strong><span className="tag">{running ? 'Processando' : job.status === 'concluido' ? 'Concluído' : 'Interrompido'}</span></header><pre aria-label="Log de atualização">{job.linhas.join('\n')}</pre></div>}
      <div className="gemini-setup"><span className="eyebrow">Inteligência artificial</span><h3>{base.ia_configurada ? 'Gemini configurado' : 'Configure sua chave gratuita'}</h3><p>Crie uma chave em <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener noreferrer">Google AI Studio</a>, coloque-a no arquivo <code>.env</code> na raiz e reinicie a aplicação.</p><pre>GEMINI_API_KEY=sua_chave{ '\n' }GEMINI_MODEL={base.modelo_ia}</pre><p className="help-text">Use um projeto no nível gratuito. A disponibilidade depende das cotas da conta; a aplicação não ativa faturamento. No serviço gratuito, o Google pode usar o conteúdo enviado para melhorar seus produtos. <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer">Termos do Gemini</a></p></div>
    </div>
  </section>;
}
