import { expect, test } from '@playwright/test';

test('publicação integral preserva contatos, mapa local e código público', async ({ page, request }) => {
  const errors: string[] = [];
  const contentPolicyErrors: string[] = [];
  const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && /Content Security Policy/i.test(message.text())) contentPolicyErrors.push(message.text()); });
  page.on('request', req => { if (req.url().startsWith('http') && new URL(req.url()).origin !== new URL(process.env['CEARA_BASE_URL'] || 'http://127.0.0.1:3000').origin) external.push(req.url()); });
  await page.goto('/');
  await expect(page.getByText('680.298', { exact: true })).toBeVisible();
  await expect(page.locator('.map-canvas canvas')).toBeVisible();
  await expect(page.locator('.app-shell')).toHaveCSS('display', 'flex');
  expect((await page.locator('.map-panel').boundingBox())!.height).toBeGreaterThan(400);
  await expect(page.locator('.map-status')).toHaveCount(0);
  await expect(page.getByRole('navigation').getByRole('button', { name: 'Assistente', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Mapa de ruas', exact: true })).toHaveCount(0);
  await page.getByRole('navigation').getByRole('button', { name: 'Empresas', exact: true }).click();
  await expect(page.locator('.contacts-table tbody tr')).toHaveCount(50);
  await expect(page.getByLabel('Bairro')).toBeVisible();
  await expect(page.locator('.contacts-table thead')).toContainText('Contato');
  await expect(page.locator('.publication-note')).toContainText('Dados Abertos CNPJ da Receita Federal');
  await expect(page.locator('.publication-note')).toContainText('Casa dos Dados');
  await page.getByLabel('Buscar empresas').fill('padaria');
  await expect(page.locator('.active-filters')).toContainText('padaria');
  await expect(page.locator('.contacts-table tbody tr')).toHaveCount(50);
  await page.locator('.company-name').first().click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog).toContainText('CNPJ');
  await expect(dialog.locator('.detail-list')).toContainText('E-mail');
  await expect(dialog.locator('.detail-list')).toContainText('Telefone');
  await expect(dialog.locator('.detail-list')).toContainText('Endereço');
  await expect(dialog.locator('.detail-list')).toContainText('Bairro');
  await expect(dialog.locator('.detail-list')).toContainText('Texto de busca');
  expect(await dialog.getByRole('link').count()).toBeGreaterThan(0);
  await dialog.getByRole('button', { name: 'Solicitar correção ou retirada' }).click();
  await expect(page.getByRole('heading', { name: 'Responsável e atendimento', exact: true })).toBeVisible();
  await expect(page.locator('.privacy-content')).toContainText('chat público está desativado');
  await expect(page.getByRole('link', { name: 'Código e execução local', exact: true })).toHaveAttribute('href', 'https://github.com/rabpaulo/mapa-oportunidade');
  await expect(page.getByRole('link', { name: 'Código desta versão', exact: true })).toHaveAttribute('href', '/codigo-fonte.tar.gz');
  await expect(page.locator('.privacy-content')).toContainText('base local integral');
  await page.screenshot({ path: 'test-results/privacidade-publica.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('navigation').getByRole('button', { name: 'Mapa', exact: true }).click();
  await expect(page.locator('.map-canvas canvas')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/mapa-publico-mobile.png', fullPage: true });
  expect(external).toEqual([]);
  expect(errors).toEqual([]);
  expect(contentPolicyErrors).toEqual([]);
  const search = await request.post('/api/contatos/buscar', { data: {} });
  expect(search.status()).toBe(200);
  const body = await search.json();
  for (const item of body.itens) expect(Object.keys(item).sort()).toEqual(['abertura', 'bairro', 'busca', 'cidade', 'cnpj', 'cod_municipio', 'dominio_proprio', 'email', 'empresa', 'endereco', 'id', 'nome', 'oportunidade', 'porte', 'score', 'segmento', 'telefone', 'tem_celular', 'whatsapp']);
  expect(body.total).toBe(680298);
  const info = await (await request.get('/api/base')).json();
  expect(info.perfil_dados).toBe('integral');
  expect(info.hospedagem_publica).toBe(true);
  expect(info.publicacao_restrita).toBe(false);
  expect((await request.post('/api/chat', { data: { pergunta: 'Olá' } })).status()).toBe(403);
});
